### PR TITLE
Fixed overflow error on 1 character text

### LINKED ISSUE #488: Overflow error is thrown by SetPath method of SvgTextBase class
Overflow error is thrown by SetPath method of SvgTextBase class when a text element contains a tspan element to format it and it contains just one character. You can find the problem on following line:
https://github.com/vvvv/SVG/blob/43f5accbffdf156fd2aa052ac8522fd48551a3f3/Source/Text/SvgTextBase.cs#L371

The state.NumChars is 1 and the origState.NumChars is 0, so it cause that the origState.LetterSpacingAdjust contains an infinity value and it produces an overflow error. This problem doesn't happen when there are more than one character or there aren't tspan elements as content of the text element.
See following StackTrace:

```
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawPath(Pen pen, GraphicsPath path)
   at Svg.SvgRenderer.DrawPath(Pen pen, GraphicsPath path) in D:\Samples\SVG-nuget2.4.3\Source\Rendering\SvgRenderer.cs:line 76
   at Svg.SvgVisualElement.RenderStroke(ISvgRenderer renderer) in D:\Samples\SVG-nuget2.4.3\Source\Basic Shapes\SvgVisualElement.cs:line 343
   at Svg.SvgVisualElement.RenderFillAndStroke(ISvgRenderer renderer) in D:\Samples\SVG-nuget2.4.3\Source\Basic Shapes\SvgVisualElement.cs:line 216
   at Svg.SvgTextBase.Render(ISvgRenderer renderer) in D:\Samples\SVG-nuget2.4.3\Source\Text\SvgTextBase.cs:line 246
   at Svg.SvgElement.RenderChildren(ISvgRenderer renderer) in D:\Samples\SVG-nuget2.4.3\Source\SvgElement.cs:line 802
   at Svg.SvgTextBase.Render(ISvgRenderer renderer) in D:\Samples\SVG-nuget2.4.3\Source\Text\SvgTextBase.cs:line 247
   at Svg.SvgElement.RenderChildren(ISvgRenderer renderer) in D:\Samples\SVG-nuget2.4.3\Source\SvgElement.cs:line 802
   at Svg.SvgVisualElement.Render(ISvgRenderer renderer, Boolean renderFilter) in D:\Samples\SVG-nuget2.4.3\Source\Basic Shapes\SvgVisualElement.cs:line 168
   at Svg.SvgVisualElement.Render(ISvgRenderer renderer) in D:\Samples\SVG-nuget2.4.3\Source\Basic Shapes\SvgVisualElement.cs:line 129
   at Svg.SvgGroup.Render(ISvgRenderer renderer) in D:\Samples\SVG-nuget2.4.3\Source\Document Structure\SvgGroup.cs:line 55
   at Svg.SvgElement.RenderChildren(ISvgRenderer renderer) in D:\Samples\SVG-nuget2.4.3\Source\SvgElement.cs:line 802
   at Svg.SvgVisualElement.Render(ISvgRenderer renderer, Boolean renderFilter) in D:\Samples\SVG-nuget2.4.3\Source\Basic Shapes\SvgVisualElement.cs:line 168
   at Svg.SvgVisualElement.Render(ISvgRenderer renderer) in D:\Samples\SVG-nuget2.4.3\Source\Basic Shapes\SvgVisualElement.cs:line 129
   at Svg.SvgGroup.Render(ISvgRenderer renderer) in D:\Samples\SVG-nuget2.4.3\Source\Document Structure\SvgGroup.cs:line 55
   at Svg.SvgElement.RenderChildren(ISvgRenderer renderer) in D:\Samples\SVG-nuget2.4.3\Source\SvgElement.cs:line 802
   at Svg.SvgElement.Render(ISvgRenderer renderer) in D:\Samples\SVG-nuget2.4.3\Source\SvgElement.cs:line 790
   at Svg.SvgFragment.Render(ISvgRenderer renderer) in D:\Samples\SVG-nuget2.4.3\Source\Document Structure\SvgFragment.cs:line 169
   at Svg.SvgDocument.Draw(ISvgRenderer renderer, ISvgBoundable boundable) in D:\Samples\SVG-nuget2.4.3\Source\SvgDocument.cs:line 428
   at Svg.SvgDocument.Draw(Bitmap bitmap) in D:\Samples\SVG-nuget2.4.3\Source\SvgDocument.cs:line 526
   at Svg.SvgDocument.Draw() in D:\Samples\SVG-nuget2.4.3\Source\SvgDocument.cs:line 506
   at SVGViewer.SVGViewer.RenderSvg(SvgDocument svgDoc) in D:\Samples\SVG-nuget2.4.3\Samples\SVGViewer\SvgViewer.cs:line 73
   at SVGViewer.SVGViewer.open_Click(Object sender, EventArgs e) in D:\Samples\SVG-nuget2.4.3\Samples\SVGViewer\SvgViewer.cs:line 30
```

You can reproduce it with the SVGViewer application and the following attached files:
[SVGs.zip](https://github.com/vvvv/SVG/files/3289663/SVGs.zip)

### PR DESCRIPTION
**Pull request by mrbean-bremen**
- fixes #488

@H1Gdev - can you have a look at this? It fixes the obvious problem (deletion by zero) and the image shows up correctly now, but I'm not sure if this is the correct fix.

### CODE REVIEW

**Comment by H1Gdev** [comment]
@mrbean-bremen 

Sorry...
`SvgTextBase` is spaghetti code, so I can not understand this unless I analyze this code deeply.

But I think that at least this issue(overflow) has been solved. . .
And it seems that there is no issue for viewing rendering result.

File: Source/Text/SvgTextBase.cs [hunk 1]
```diff
@@ -400,7 +400,8 @@ private void SetPath(TextDrawingState state, bool doMeasurements)
                         {
                             if (this.X.Count < 2)
                             {
-                                origState.LetterSpacingAdjust = -1 * diff / (state.NumChars - origState.NumChars - 1);
+                                if (state.NumChars - origState.NumChars - 1 != 0)
+                                    origState.LetterSpacingAdjust = -1 * diff / (state.NumChars - origState.NumChars - 1);
                                 SetPath(origState, false);
```
Comment (H1Gdev) [inline Source/Text/SvgTextBase.cs]: @mrbean-bremen 

I think that may be the following code because it does not change `state`.
```cs
if (state.NumChars - origState.NumChars - 1 != 0)
{
    origState.LetterSpacingAdjust = -1 * diff / (state.NumChars - origState.NumChars - 1);
    SetPath(origState, false);
    return;
}
```

Comment (mrbean-bremen) [reply Source/Text/SvgTextBase.cs]: Yes, this is the point I wasn't sure about - I don't really understand that code either... I will have a closer look later, thanks!

Comment (mrbean-bremen) [reply Source/Text/SvgTextBase.cs]: Ok, I agree with you - I changed it as you proposed..

Comment (mrbean-bremen) [reply Source/Text/SvgTextBase.cs]: @H1Gdev: On a general note - I'm not sure if I will do much for SVG.NET in the next time (I'm a bit short on time lately), but I would appreciate if you could review my stuff if you get the time. I generally prefer a second pair of eyes - @tebjan doesn't really have the time, and you seem to know quite a bit of the code already, so that would be really helpful.
