### PR TITLE
Fix issue #704. 

### LINKED ISSUE #704: Accessing SvgText.Bounds is not indempotent when a transform is applied to text.
#### Description
Repeated calls to SvgText.Bounds gives different results each time, if SvgText.Transforms is not empty.

#### Example data

Repro patch below. Adds unit tests that fail because of this issue.

#### Used Versions
version 2.4.3
https://github.com/vvvv/SVG/commit/0b4f8b79b6ad3a9e5662d7581ed665dc7ce2b4e7

```
diff -r 380a65e71c03 Tests/Svg.UnitTests/BoundsTests.cs
--- a/Tests/Svg.UnitTests/BoundsTests.cs	Fri Mar 20 08:08:27 2020 +0000
+++ b/Tests/Svg.UnitTests/BoundsTests.cs	Thu Apr 02 10:25:41 2020 +0100
@@ -36,6 +36,17 @@
         }
 
         [Test]
+        public void TestTextBounds()
+        {
+            // x="10" y="30" font-family="Tahoma" font-size="15pt"  content="VVVV-svg"
+            AssertEqualBounds("text", 9.92f, 15.46f, 83.69f, 18.67f);
+            // additional translation(10, 10)
+            AssertEqualBounds("text-xlate", 19.92f, 24.8f, 133.95f, 19.33f);
+            // additional rotation(30)
+            AssertEqualBounds("text-rot", -2.08f, 18.34f, 102.46f, 71.01f);
+        }
+
+        [Test]
         public void TestGroupBounds()
         {
             // all lines from TestLineBounds()
@@ -62,6 +73,23 @@
             AssertEqualBounds("lines-rotated", -45.5f, 9.5f, 86, 31);
         }
 
+        [Test]
+        public void TestBoundsIndempotent()
+        {
+            // ensure that accessing the Bounds property returns the same value when called repeatedly.
+            AssertEqualBounds("lines-rotated", -45.5f, 9.5f, 86, 31);
+            AssertEqualBounds("lines-rotated", -45.5f, 9.5f, 86, 31);
+
+            AssertEqualBounds("text-rot", -2.08f, 18.34f, 102.46f, 71.01f);
+            AssertEqualBounds("text-rot", -2.08f, 18.34f, 102.46f, 71.01f);
+
+            AssertEqualBounds("rect-rot", -50.5f, 9.5f, 21f, 11f);
+            AssertEqualBounds("rect-rot", -50.5f, 9.5f, 21f, 11f);
+
+            AssertEqualBounds("line-xform", 19.5f, -40.5f, 21, 21);
+            AssertEqualBounds("line-xform", 19.5f, -40.5f, 21, 21);
+        }
+
         private void AssertEqualBounds(string elementId, float x, float y, float width, float height)
         {
             const float Epsilon = 0.01f;
diff -r 380a65e71c03 Tests/Svg.UnitTests/Resources/Issue281_Bounds/BoundsTest.svg
--- a/Tests/Svg.UnitTests/Resources/Issue281_Bounds/BoundsTest.svg	Fri Mar 20 08:08:27 2020 +0000
+++ b/Tests/Svg.UnitTests/Resources/Issue281_Bounds/BoundsTest.svg	Thu Apr 02 10:25:41 2020 +0100
@@ -26,4 +26,9 @@
     <rect id="rect-xlate" x="10" y="30" width="10" height="20" transform="translate(10, 10)" />
     <rect id="rect-rot" x="10" y="30" width="10" height="20" transform="rotate(90)" />
   </g>
+  <g id="texts">
+    <text id="text" x="10" y="30" font-family="Tahoma" font-size="15pt">VVVV-svg</text>
+    <text id="text-xlate" x="10" y="30" font-family="Tahoma" font-size="15pt" transform="translate(10, 10)">VVVV-svg-xlate</text>
+    <text id="text-rot" x="10" y="30" font-family="Tahoma" font-size="15pt" transform="rotate(30)" >VVVV-svg-rot</text>
+  </g>
 </svg>
```

### PR DESCRIPTION
**Pull request by bbsgfalconer**
Transform a copy of graphics path when calculating text bounds.

Includes issue repro unit tests.

#### Reference Issue

Fixes #704

### CODE REVIEW

File: Source/Text/SvgTextBase.cs [hunk 1]
```diff
@@ -270,6 +270,7 @@ public override RectangleF Bounds
                 }
                 if (Transforms != null && Transforms.Count > 0)
                 {
+                    path = path.Clone() as GraphicsPath;    // fix issue #704
```
Comment (H1Gdev) [inline Source/Text/SvgTextBase.cs:273]: Please reference here.
https://github.com/vvvv/SVG/blob/8cf361077e64f48490a43d47b7e68758b6a25ef8/Source/Basic%20Shapes/SvgPathBasedElement.cs#L18-L26

Comment (H1Gdev) [inline Source/Text/SvgTextBase.cs:273]: remove comment.

**Comment by mrbean-bremen** [comment]
@H1Gdev - this looks good to me apart from that minor comment issue - I'm going to merge this, and this can be corrected later.

**Comment by H1Gdev** [comment]
@mrbean-bremen 

This will not dispose cloned `GraphicsPath`.
I will create new PR that fixes this issue.
